---
- name: Capture Kernel Version
  hosts: node1

  tasks:

    - name: Collect only kernel facts
      ansible.builtin.setup:
        filter:
        - '*kernel'
      register: setup

    - debug:
        var: setup
